@startuml logical flow: Audio Analysis

actor user
participant JavaScript as js
participant ExtendScript as es

participant Python as py
participant PremierePro as pp

activate user
activate pp
activate js
activate es

user -> js  : start processing
js -> es  : fetch Audio Track Data
es <<-->> pp: Get Audio Track Data
js <<-- es: return Data
js -> es: run Python


es -> py ++ : Execute Python script
py -> py ++ #LightGray :start websocket
js <- py: inform started
js -->> py: send data
par
    py -> py ++ #Gray: Process data
    js <-> py : update status
end
py -->> js --: send processed Data
js -> py: close WebSocket
deactivate py
deactivate py


js -> es: set Markers
es -> pp: set Markers in Sequence
user <<- es: alert completion
group "cutting process"
    user -> pp: review and modify\nmarkers (optional)
    user -> js: trigger cutting process
    js ->es: fetch markers
    es <--> pp: get markers
    js <<-- es: promise resolve (markers)
    js -> es:  apply Cuts
    es -> pp: cut video clips
end


deactivate js
deactivate es


@enduml
