@startuml logical flow: Audio Analysis

actor user
participant JavaScript as js
participant ExtendScript as es

participant Python as py
participant PremierePro as pp

activate user
activate pp

user -> js: start processing
activate js
js -> es: $.core.fetchAudTrackData\n(Parameters)
activate es
es <-> pp: Get Audio Track Data
es -> es: create JSON Data
js <<-- es: promise resolve (JSON Data)
js -> es: $.core.writeArgData(JSON Data)

js <<-- es: promise resolve
js -> es: $.core.runPy()

es -> py: Execute Python script
activate py
py -> py:start websocket
es <- py: inform started
es -> py: send data
par
    es <-> py: update status
    py -> py: Process data
else
    py -> es: send processed Data
end
es -> py: stop python
deactivate py

js <<-- es: promise resolve
js -> es: $.core.setMarkers()

es -> pp: set Markers in Sequence
user <<-- es: alert completion
box "cutting process" #LightBlue
    user -> pp: review and modify\nmarkers
    user -> js: trigger cutting process
    js -> es: $.core.applyCuts()
    es -> pp: repostion video clips
end box


deactivate js
deactivate es


@enduml
